apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: chat-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
     - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage
  hostPath:
     path: "/mnt/kind-data" 
